# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['pdfvoz.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'edge_tts',
        'pyttsx3',
        'pyttsx3.drivers',
        'pyttsx3.drivers.sapi5',
        'sounddevice',
        'soundfile',
        'fitz',
        'ebooklib',
        'ebooklib.epub',
        'aiohttp',
        'aiohappyeyeballs',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='pdfvoz-gui',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
